### ISSUE TITLE
Error parsing ternary operator

### ISSUE THREAD

**Issue by SeriyBg** [kaitai-io/kaitai_struct_compiler#119]
When trying to parse ternary `.ksy` file that contains ternary operator `value: condition ? if_true : if_false` with
```
kaitai-struct-compiler -t java --java-package com.my.struct.package --verbose file mystruct.ksy
```
receiving an error:

```
parsing mystruct.ksy...
reading mystruct.ksy...
mapping values are not allowed here
 in 'reader', line 194, column 44:
     ... e: length % 8 == 0 ? length / 8 : length / 8 + 1
                                         ^
```
The same .ksy file works in web IDE.
Also, there is workaround:
`value: 'condition ? if_true : if_false'`

If it is the expected behavior, then It would be good to mention it in the documentation

**Comment by GreyCat** [comment]
* Please don't create issues in this project, as mentioned in the first line of README. Use [main project](https://github.com/kaitai-io/kaitai_struct/issues).
* Yes, it is known and expected behavior, given that we want to be 100% compatible with YAML. Probably it's a good idea to mention it in the documentation, though.

**Comment by GreyCat** [comment]
I've added some caution words to the documentation: http://doc.kaitai.io/user_guide.html#_ternary_if_then_else_operator

Thanks for the report!

**Comment by SeriyBg** [comment]
Thanx! I was a little confused with the issue.
