### ISSUE TITLE
Exception in thread "main" java.lang.RuntimeException: Unable to access config_field in List(fmts_header) context

### ISSUE THREAD

**Issue by tschoening** [kaitai-io/kaitai_struct_compiler#31]
I have three KSY files each containing some types and representing some kind of container data: Datagram is all the data and contains a header, which contains a config_field. Each of those has one KSY file. The datagram of course is not only a header, but has a payload as well, the length of the payload depends on the config_field in the header. So what I ultimately trying to achieve is accessing the header.config_field in the datagram to know how many bytes I need to read for the payload.

For test purposes I simply hard coded the length of the payload, the generation of Java classes work this way and I can see that the class structure and their visibility should be able to provide what I need. There is a public getter for the header, which has a public getter for the config_field etc.

So, is my approach wrong and can't work for some reason or is this  bug?

Datagram:

    meta:
      id:      fmts_datagram
      endian:  le
    
    seq:
      - id:   header
        type: fmts_header
      - id:   enc_payload
        size: header.config_field.aes_byte_cnt # TODO recognize missing MEH C-Field
        #if:   header.config_field.aes_byte_cnt > 0
    #  - id:    dec_payload
    #    size:  header.length - 14 # TODO recognize missing MEH C-Field
    #    if:    header.config_field.aes_byte_cnt == 0

Header:

    meta:
      id:      fmts_header
      endian:  le
    
    seq:
      - id:   length
        type: u1
        doc:  Length of datagram without CRC bytes.
    [...]
      - id:   config_field
        type: fmts_config_field
    
    instances:
    [...]

ConfigField:

    meta:
      id:      fmts_config_field
      endian:  le
    
    seq:
      - id:   lsb
        type: u1
      - id:   msb
        type: u1
    
    instances:
      enc_mode:
        value: msb & 0x0F
      aes_blk_cnt:
        value: lsb >> 4
      aes_byte_cnt:
        value: aes_blk_cnt * 16

**Comment by GreyCat** [comment]
Yeah, as I said, right now all files are compiled effectively separately. That means that you can, for example, ask to compile "Datagram" without having all the other .ksys on the command line or in the same directory, or whatever - and the result will be exactly the same as compiling it together with

```
ksc -t java fmts_datagram.ksy fmts_header.ksy fmts_config_field.ksy
```

That means that accessing `header.config_field` is impossible: for a compiler, `header` is just some unknown, opaque type. During compilation of `fmts_datagram.ksy`, compiler doesn't have any information about internals of `header`, which fields it contains, which types are they, etc, etc. - and it needs that information to evaluation of the expression in `size` properly.

So, to summarize: it is impossible right now. Referencing types in other files works in simple, "opaque" cases - i.e. when you just ask for them to be instanced, or reference them whole. You can't access object's internals - i.e. `seq` attributes, `instances` attributes, `enums`, etc.

I can offer several solutions:

1. Simplest one - obviously, put everything in one file manually. To some extent, that is per design - i.e. stacking network protocols works that way exactly because there should be no inter
2. Simple one - add an extra step to your build system that will concatenate all your protocol ksy files into one automatically during the build. Here's a short Ruby script that does that, for example:

```ruby
require 'yaml'
doc = YAML.load(File.read(ARGV.shift))
ARGV.each { |fn|
  doc2 = YAML.load(File.read(fn))
  doc['types'][doc2['meta']['id']] = doc2
  doc2['meta'].delete('id')
}
puts doc.to_yaml
```

3. Long one - discuss implementation of more-than-one file compilation with us and wait for it to be implemented.

**Comment by tschoening** [comment]
Thanks again for your explanation. I must admit I don't really understand how your code generation works if things are possible in the resulting generated Java code, but not during the phase when this code is created... :-)

Are you creating some intermediate types which need to be working in whatever type system you create them and are generating textual Java or other language output only afterwards? I thought you were parsing YAML and directly generating the output language of choice more like a textual template engine mapping YAML statements to target language logic blocks and statements and such.

Anyway, I guess I'll have a look at your second suggestion or try to rewrite my files.

**Comment by GreyCat** [comment]
It's more or less as you've described, but there are several preparation steps:

1. **Class names markup**. We start with a YAML-like structure, every node by itself. It's impossible to say absolute path to type node without doing some pre-markup. This is trivial recursive descent: for example, if top-level type has `/meta/id` equal to `foo`, and we have nodes nested like `/types/bar/types/baz`, it will mark that up as `foo::bar::baz`.
2. **Resolving user types**. One may write `type: foo` almost everywhere, but what does it mean actually? It's not really trivial, as different programming languages have different semantics there. We universally adopt Java and Ruby-like semantics (i.e. we search for `foo` on current nesting level, then we check a level above, then above, etc, etc, up to the very top). Once done, we have a solid understanding of what exactly does that `type: foo` means. If we haven't found `foo` in our current file, we assume that it's a top-level type in some other file and handle it as "opaque" top-level type, assuming that we know nothing about it.
3. **Deriving types for value instances**. Value instances (ones that only have `value` and not actually parse anything from source stream) need their types derived, so we'd properly declare them for statically typed languages. This involves analyzing the expressions and deriving the types.
4. **Parent types markup**. That's the most controversial stuff: one needs to calculate which type will be `_parent` if it's called from a given type. This, again, involves traversal of all types hierarchy, but this time using usage as links, not declarations.
