### ISSUE TITLE
Parentheses are lost from expressions

### ISSUE THREAD

**Issue by koczkatamas** [kaitai-io/kaitai_struct_compiler#54]
`1 and (2 or 3)` and `(1 and 2) or 3` are also converted to `1 && 2 || 3` (JavaScript), so the parentheses are lost from the expressions.

**Comment by GreyCat** [comment]
This example with 1-2-3 nowadays yields a compilation error due to type mismatch (boolean operation applied to numeric values).

Doing it with a-b-c yields:

* `a and (b or c)` => `((this.a) && ( ((this.b) || (this.c)) ))`
* `(a and b) or c` => `(( ((this.a) && (this.b)) ) || (this.c))`

That's way too many parenthesis, but at least it gets valid output. Thus I'm closing this one for now, continuation of this parenthesis correction should happen in https://github.com/kaitai-io/kaitai_struct/issues/69.
